name: finki-scraper
services:
  scraper:
    container_name: finki-scraper
    image: ghcr.io/delemangi/finki-scraper:latest
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./logs:/app/logs
