version: '3.8'

services:
  scraper:
    container_name: finki-scraper-dev
    image: finki-scraper-dev:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./logs:/app/logs
