version: "3.8"

services:
  scraper:
    container_name: finki-scraper
    image: delemangi/finki-scraper
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./logs:/app/logs
