version: '3.8'

services:
  scraper:
    container_name: finki-scraper
    image: finki-scraper
    build: .
    restart: always
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./bot.log:/app/bot.log
