name: finki-scraper-server

services:
  scraper:
    container_name: finki-scraper-server
    image: delemangi/finki-scraper:latest
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./logs:/app/logs
    entrypoint: ["npm", "run", "serve"]
    ports:
      - 3000:3000
